# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Criar e implantar aplicativo Python no Azure Web App - redirecionador-webhook-pdv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar a versão Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Criar e iniciar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Compactar artefato para implantação
        run: zip release.zip ./* -r

      - name: Carregar artefato para trabalhos de implantação
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #Isto é necessário para solicitar o JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descompactar artefato para implantação
        run: unzip release.zip

      
      - name: Login Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_463104B433974EDDA36E29D2DA7A1264 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DCDF8EBD47264F99BD1343A9CD2F3361 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_856E4734C5F842C891F2EDD9C65252ED }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'redirecionador-webhook-pdv'
          slot-name: 'Production'
          